spring:
  application:
    name: bank-farnsi
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/insuranced
    driverClassName: org.postgresql.Driver
    username: alpha
    password: alpha
    platform: org.hibernate.dialect.Postgresql

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect



springdoc:
  api-docs:
    path: /swagger/experience-${spring.application.name}-api-1.0.yml
    enabled: true
  swagger-ui:
    path: '/swagger-ui'
    url: /swagger/experience-${spring.application.name}-api-1.0.yml
    doc-expansion: none
    disable-swagger-default-url: true
  packagesToScan: 'bfs.digital.fransi.api.controller'
  pathsToMatch: '/protected/**'

server:
  port: 8080

