spring:
  application:
    name: bank-farnsi
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/insuranced
    driverClassName: org.postgresql.Driver
    username: alpha
    password: alpha
    platform: org.hibernate.dialect.Postgresql

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


server:
  port: 8080

